---
- name: Testing andrewrothstein.uaa
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'uaa version'...
      ansible.builtin.command: uaa version
      changed_when: false
      register: uaa_test_output
    - name: Output from 'uaa version'
      ansible.builtin.debug:
        msg: '{{ uaa_test_output.stdout }}'
